import{w as a,q as e}from"./index-CLLJqTva.js";import"./index-BMu1d4kC.js";import{S as o,a as d}from"./index-CP53eZP4.js";import{I as s,R as t,H as n,a as c}from"./index-Dq_L-XFB.js";import{s as h}from"./java-CnbYup62.js";import"./index-H-X4gc9i.js";const x="/assets/pseudocode%20example-DWenZZms.jpg",j="/assets/start-node-DT-q6ujZ.png",p="/assets/down-arrow-C2QfLnbS.png",u="/assets/decision-node-DAqPzuqM.png",w="/assets/process-node-jOIwf-ZR.png",f="/assets/output-node-sxezxEDp.png",i="Day 15: Exceptional Design",m=["Quiz 6","Exception Handling","Program Design","In Class: Pseudocode"],y=()=>e.jsxs(e.Fragment,{children:[e.jsx(o,{title:i,downloadHref:h}),e.jsxs(d,{children:[e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:i})}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Agenda"}),e.jsx("ul",{className:"list-disc",children:m.map((r,l)=>e.jsx("li",{children:r},l))})]}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"Quiz 6"})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"Exception Handling"})}),e.jsx("section",{children:e.jsx("p",{children:"Our code can sometimes crash when we give it values we don't intend to give or try to use values that we don't have access to."})}),e.jsxs("section",{children:[e.jsxs("p",{children:["We've seen these with ",e.jsx("code",{children:"ArrayIndexOutOfBoundsExceptions"})," and ",e.jsx("code",{children:"IndexOutOfBoundsExceptions"}),". Some of you have also seen the ",e.jsx("code",{children:"InputMismatchException"})," and the ",e.jsx("code",{children:"NullPointerException"})]}),e.jsx("p",{children:"In Java, errors are called exceptions."})]}),e.jsx("section",{children:e.jsxs("p",{children:["We can ",e.jsx("code",{children:"try"})," to run some code that may crash then ",e.jsx("code",{children:"catch"})," the exceptions."]})}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Template"}),e.jsxs("div",{className:"font-mono text-[16pt] text-left",children:[e.jsx(s,{children:"try {"}),e.jsx(s,{space:2,children:"// Code that might crash"}),e.jsx(s,{children:"}"}),e.jsx(s,{children:"catch(<Exception> e) { // should be specific exception"}),e.jsx(s,{space:2,children:"// What to do if exception is hit?"}),e.jsx(s,{children:"}"})]})]}),e.jsx("section",{children:e.jsxs(t,{children:[e.jsx(n,{children:e.jsxs("p",{children:["The code to the right tries to get a value in an array at index ",e.jsx("code",{children:"i"}),", but if the index is out of bounds, instead of crashing, we return ",e.jsx("code",{children:"-1"})]})}),e.jsxs(c,{children:[e.jsx(s,{children:"private static int getN(int[] arr, int i) {"}),e.jsx(s,{space:1,children:"try {"}),e.jsx(s,{space:2,children:"return arr[i];"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{space:1,children:"catch(ArrayIndexOutOfBoundsExceptions e) {"}),e.jsx(s,{space:2,children:"return -1;"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{children:"}"})]})]})}),e.jsx("section",{children:e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:`You may be thinking "why don't we just use an if-statement and check if the index is out of bounds". You would be correct to think of this.`})}),e.jsxs(c,{children:[e.jsx(s,{children:"private static int getN(int[] arr, int i) {"}),e.jsx(s,{space:1,children:"try {"}),e.jsx(s,{space:2,children:"return arr[i];"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{space:1,children:"catch(ArrayIndexOutOfBoundsExceptions e) {"}),e.jsx(s,{space:2,children:"return -1;"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{children:"}"})]})]})}),e.jsx("section",{children:e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:"This example isn't the greatest because we can catch the exception without needing to use a try-catch with the code."})}),e.jsxs(c,{children:[e.jsx(s,{children:"private static int getN(int[] arr, int i) {"}),e.jsx(s,{space:1,children:"try {"}),e.jsx(s,{space:2,children:"return arr[i];"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{space:1,children:"catch(ArrayIndexOutOfBoundsExceptions e) {"}),e.jsx(s,{space:2,children:"return -1;"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{children:"}"})]})]})}),e.jsx("section",{children:e.jsxs(t,{children:[e.jsx(n,{children:e.jsxs("p",{children:["This is what we call an ",e.jsx("code",{children:"unchecked"})," exception."]})}),e.jsxs(c,{children:[e.jsx(s,{children:"private static int getN(int[] arr, int i) {"}),e.jsx(s,{space:1,children:"try {"}),e.jsx(s,{space:2,children:"return arr[i];"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{space:1,children:"catch(ArrayIndexOutOfBoundsExceptions e) {"}),e.jsx(s,{space:2,children:"return -1;"}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{children:"}"})]})]})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"Checked v Unchecked Exceptions"})}),e.jsx("section",{children:e.jsxs(t,{children:[e.jsxs(n,{children:[e.jsx("p",{children:"An unchecked exception is an exception that happens when the code being executed runs into logical errors. These aren't checked at compile time, as they would only occur based on the usage of the code/values given into the code. These are often also errors we can find with a simple if-statement ahead of time."}),e.jsx("p",{children:"Examples are:"}),e.jsxs("ul",{children:[e.jsx("li",{children:"NullPointerException"}),e.jsx("li",{children:"ArrayIndexOutOfBoundsExceptions"})]})]}),e.jsxs(n,{children:[e.jsx("p",{children:"Checked exceptions happen when the code is compiled. These often are more complicated and cannot simply be checked with an if-statement. Instead, we must check for these exceptions using a try-catch statement."}),e.jsx("p",{children:"Examples are:"}),e.jsxs("ul",{children:[e.jsx("li",{children:"FileNotFoundException"}),e.jsx("li",{children:"IOException"})]})]})]})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"finally"})}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"finally"}),e.jsxs(t,{children:[e.jsxs(n,{children:[e.jsxs("p",{children:["Similar to Python, if we had code that should always execute no matter what happens, we can use the ",e.jsx("code",{children:"finally"})," clause."]}),e.jsx("p",{children:'Example to the right will always print out "Swap done!"'})]}),e.jsxs(c,{children:[e.jsx(s,{children:"static void swap(float[] arr, int i, int j){"}),e.jsx(s,{space:1,children:"try {"}),e.jsx(s,{space:2,children:"float t = arr[i];"}),e.jsx(s,{space:2,children:"arr[i] = arr[j];"}),e.jsx(s,{space:2,children:"arr[j] = t;"}),e.jsx(s,{space:1,children:"} catch(ArrayIndexOutOfBoundsExceptions e) {"}),e.jsx(s,{space:2,children:'System.out.println("Error with index!");'}),e.jsx(s,{space:1,children:"} finally {"}),e.jsx(s,{space:2,children:'System.out.println("Swap done!");'}),e.jsx(s,{space:1,children:"}"}),e.jsx(s,{space:0,children:"}"})]})]})]}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Why?"}),e.jsxs("p",{children:[e.jsx("code",{children:"try/catch"})," pattern is great when we need to write some code that may or may not crash."]}),e.jsxs("p",{children:[e.jsx("code",{children:"finally"})," is great for cleaning up the code to ensure some code is always executed. This can show up when we need to close a Scanner or close a file."]}),e.jsxs("p",{children:["Since ",e.jsx("code",{children:"finally"})," always happens at the end, if you return a value in the ",e.jsx("code",{children:"finally"}),"block and return a value in the ",e.jsx("code",{children:"try"})," block, the value returned in ",e.jsx("code",{children:"finally"})," will be returned."]})]}),e.jsx("section",{children:e.jsxs("div",{className:"font-mono text-left text-[16pt]",children:[e.jsx(s,{children:"try {"}),e.jsx(s,{space:2,children:"return 1;"}),e.jsx(s,{children:"} catch(Exception e) { // Generic exception, catch all"}),e.jsx(s,{space:2,children:"return -1;"}),e.jsx(s,{children:"} finally {"}),e.jsx(s,{space:2,children:"return 0; // returns 0 since finally runs last."}),e.jsx(s,{children:"}"})]})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"throws"})}),e.jsx("section",{children:e.jsxs("p",{children:["If we wanted to raise an exception (like we could in Python), we would need to use the ",e.jsx("code",{children:"throws"})," and ",e.jsx("code",{children:"throw"})," keyword."]})}),e.jsx("section",{children:e.jsxs("p",{children:["We add the ",e.jsx("code",{children:"throws"})," keyword to the method itself, which tells Java that this method would eventually throw a specific exception. We also include the specific exception it may throw."]})}),e.jsx("section",{children:e.jsxs("div",{className:"text-left font-mono text-[16pt]",children:[e.jsx(s,{children:"static void swap(int[] arr, int i, int j) throws ArrayIndexOutOfBoundsExceptions {"}),e.jsx(s,{space:2,children:"int t = arr[i];"}),e.jsx(s,{space:2,children:"arr[i] = arr[j];"}),e.jsx(s,{space:2,children:"arr[j] = t;"}),e.jsx(s,{children:"}"})]})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"But why?"})}),e.jsxs("section",{children:[e.jsx("p",{children:"Having a method throw an exception can be better to ensure the calling location can handle the exception differently."}),e.jsx("p",{children:"Forcing a way of handling an exception isn't always great, sometimes we want to allow whatever is calling the function to handle it themselves."})]}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"throw"})}),e.jsx("section",{children:e.jsxs("p",{children:["Now, if we want to intentionally throw an exception, we can use the ",e.jsx("code",{children:"throw"})," keyword with the ",e.jsx("code",{children:"throws"})," keyword."]})}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Example"}),e.jsxs("div",{className:"font-mono text-left text-[16pt]",children:[e.jsx(s,{children:"static int findMax(int[] arr) throws IndexOutOfBoundsExceptions {"}),e.jsx(s,{space:2,children:"if(arr.length == 0) {"}),e.jsx(s,{space:4,children:'throw new IndexOutOfBoundsExceptions("empty array!");'}),e.jsx(s,{space:2,children:"}"}),e.jsx(s,{space:2,children:"// find max implementation"}),e.jsx(s,{children:"}"})]})]}),e.jsx("section",{children:e.jsxs("p",{children:[e.jsx("code",{children:"throw"})," will end the function once the exception is thrown. This is useful if we want to implement different ways to process the errors elsewhere, rather than within the function itself."]})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"5 min break; topic pivot after break"})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"Program Design"})}),e.jsxs("section",{children:[e.jsx("p",{children:"For the rest of this week, we'll look at two forms of pseudocode that help us structure our code."}),e.jsxs("p",{children:["The first, which will be today is called ",e.jsx("strong",{children:"Flowchart Pseudocode"})]})]}),e.jsx("section",{children:e.jsx("p",{children:"So what is Pseudocode?"})}),e.jsx("section",{children:e.jsxs("p",{children:["For the exercises today, we will use the website ",e.jsx("a",{href:"https://app.diagrams.net",target:"_blank",children:"app.diagrams.net"}),". It's posted on the course page under the resources for today as ",e.jsx("strong",{children:"Diagram Tool"})]})}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"Flowchart Pseudocode"})}),e.jsx("section",{children:e.jsx("p",{children:"We can model a function using a flowchart, where certain symbols represent certain concepts."})}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Terminal"}),e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:"Often to denote a program start or end point."})}),e.jsx(n,{children:e.jsx("img",{src:j,alt:"Start/End"})})]})]}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Flow Direction"}),e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:"Denotes the direction of flow."})}),e.jsx(n,{children:e.jsx("img",{src:p,alt:"Down arrow"})})]})]}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Input/Output"}),e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:"Denotes the input or output of data (user input, console output)"})}),e.jsx(n,{children:e.jsx("img",{src:f,alt:"Output x"})})]})]}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Process"}),e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:"Denotes an operation that manipulates data. This can be changing the value of a variable or manipulating it."})}),e.jsx(n,{children:e.jsx("img",{src:w,alt:"x = 1"})})]})]}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Decision"}),e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("p",{children:"Denotes a condition or decision made that redirects the flow of data based on the conditional outcome (if statement)"})}),e.jsx(n,{children:e.jsx("img",{src:u,alt:"x < 3?"})})]})]}),e.jsxs("section",{children:[e.jsx("p",{className:"text-usf-yellow",children:"Flowchart Example"}),e.jsxs(t,{children:[e.jsx(n,{children:e.jsx("img",{src:x,alt:"example flowchart pseudocode"})}),e.jsxs(c,{children:[e.jsx(s,{children:"int counter = 1;"}),e.jsx(s,{children:"while(counter < 100) {"}),e.jsx(s,{space:1,children:"System.out.println(counter);"}),e.jsx(s,{space:1,children:"counter++;"}),e.jsx(s,{children:"}"})]})]})]}),e.jsx("section",{children:e.jsx("p",{className:"text-usf-yellow",children:"Inclass: Pseudocode"})}),e.jsx("section",{children:e.jsxs("p",{children:["Using the ",e.jsx("a",{href:"https://app.diagrams.net",target:"_blank",children:"app.diagrams.net"})," website, you will draw the pseudocode for the programs shown in the inclass assignment."]})})]})]}),k=a(y);export{k as default};
